---
- name: PIX installer for winOS
  hosts: localhost  # Run tasks on the Ansible control node
  gather_facts: false
  vars:
    source: "/home/eng/apps/winOS/pix/PIX-3.5.6.exe"

  tasks:
    - name: Install ClamAV
      become: yes
      package:
        name: clamav
        state: present

    - name: Scan downloaded file with ClamAV
      command: clamscan --stdout "{{ source }}"
      register: clamav_result
      changed_when: false

    - name: Fail if virus found
      fail:
        msg: "Virus detected in the downloaded file!"
      when: "'FOUND' in clamav_result.stdout"

- name: Install PIX
  hosts: "{{ target }}"
  vars_files:
    - "{{ lookup('env', 'ANSIBLE_ENV') }}"
  vars:
    source: "/home/eng/apps/winOS/pix/PIX-3.5.6.exe"
    endpoint: C:\Users\Public\Desktop\pix.exe
  tasks:

  #Install MSI/.exe software 
    - name: Copy executable
      ansible.builtin.copy:
        src: "{{ source }}"
        dest: "{{ endpoint }}"

    - name: Check PIX is install through win_package
      win_package:
        path: C:\Users\Public\Desktop\pix.exe
        state: present
    
    - name: Pause to allow installation to complete
      pause:
        seconds: 10