---
- name: Install default apps 
  hosts: "{{ target }}" 
  gather_facts: false
  tasks: 
#Upgrade all instaled packages  
  - name: Upgrade installed packages
    win_chocolatey:
      name: all
      state: latest
   
  - name: install adobeReader
    win_chocolatey:
      name: adobereader
      state: present
    
  - name: Upgrade installed packages
    win_chocolatey:
      name: all
      state: latest
   
  - name: install dropbox
    win_chocolatey:
      name: dropbox
      state: present