- name: Microsoft Office 365 for macOS devices
  hosts: localhost  # Run tasks on the Ansible control node
  gather_facts: false
  vars:
    check_file: "/home/eng/apps/macOS/microsoft_office/Microsoft_365_and_Office_16.81.24011420_BusinessPro_Installer.pkg"
  
  tasks:
    - name: Install ClamAV
      become: yes
      package:
        name: clamav
        state: present

    - name: Scan .pkg file with ClamAV
      command: clamscan --stdout "{{ check_file }}"
      register: clamav_result
      changed_when: false

    - name: Fail if virus found
      fail:
        msg: "Virus detected in the downloaded file!"
      when: "'FOUND' in clamav_result.stdout"

- name: Install 365 Office Suite
  hosts: " {{ target }} "
  tasks:
    - name: Copy PKG Installer
      ansible.builtin.copy:
        src: /home/eng/apps/macOS/microsoft_office/Microsoft_365_and_Office_16.81.24011420_BusinessPro_Installer.pkg
        dest: /tmp/Microsoft365.pkg

    - name: Install App
      command: sudo installer -pkg /tmp/Microsoft365.pkg -target /
      become: yes

    - name: Delete .pkg specified
      file:
        path: "/tmp/Microsoft365.pkg"
        state: absent

