---
- name: Install 365 Office Suite
  hosts: " {{ target }} "
  tasks:
    - name: Copy PKG Installer
      ansible.builtin.copy:
        src: /home/eng/apps/Microsoft_365_and_Office_16.81.24011420_BusinessPro_Installer.pkg
        dest: /tmp/Microsoft365.pkg

    - name: Install App
      command: sudo installer -pkg /tmp/Microsoft365.pkg -target /
      become: yes

    - name: Delete .pkg specified
      file:
        path: "/tmp/Microsoft365.pkg"
        state: absent

