---
- name: Check .dmg installer checksum
  hosts: "{{ target }}"
  gather_facts: false
  tasks:

    - name: Copy PKG Installer
      ansible.builtin.copy:
        src: /home/eng/apps/Adobe_Creative_Cloud.zip
        dest: /tmp/creative_cloud.zip

    - name: Unzip the application
      command: "unzip -o /tmp/creative_cloud.zip -d /Applications"

    - name: Install from installer.app
      command: "sudo installer -pkg /Applications/Adobe\\ Creative\\ Cloud/Build/Adobe\\ Creative\\ Cloud_Install.pkg -target /"
      become: yes

    - name: Pause to allow installation to complete
      pause:
        seconds: 10

    - name: Copy shortcut
      command: "sudo cp -R /Applications/Adobe\\ Creative\\ Cloud/Adobe\\ Creative\\ Cloud /Applications/Adobe\\ Creative\\ Cloud.app"
      become: yes
    
    - name: Clean up the downloaded .zip file
      file:
        path: "/tmp/creative_cloud.zip"
        state: absent