---
- name: Check .dmg installer checksum and scan for virus
  hosts: localhost  # Run tasks on the Ansible control node
  gather_facts: false
  vars:
    check_file: "/home/eng/apps/bit_defender.dmg"
  
  tasks:
    - name: Install ClamAV
      become: yes
      package:
        name: clamav
        state: present

    - name: Scan .dmg file with ClamAV
      command: clamscan --stdout "{{ check_file }}"
      register: clamav_result
      changed_when: false

    - name: Fail if virus found
      fail:
        msg: "Virus detected in the downloaded file!"
      when: "'FOUND' in clamav_result.stdout"

- name: Check .dmg installer checksum
  hosts: "{{ target }}"
  gather_facts: false

  tasks:
    - name: Copy DMG Installer
      ansible.builtin.copy:
        src: /home/eng/apps/bit_defender.dmg
        dest: /tmp/bit_defender.dmg

    - name: Check if volume is already mounted
      shell: hdiutil info | grep "/Volumes/Endpoint for MAC"
      ignore_errors: true
      register: is_volume_mounted

    - name: Mount DMG if not already mounted
      command: hdiutil attach -nobrowse -mountpoint "/Volumes/Endpoint for MAC" "/tmp/bit_defender.dmg"
      when: is_volume_mounted.rc != 0

    - name: Debug path existence
      debug:
        msg: "Path exists: {{ '/Volumes/Endpoint for MAC/SetupDownloader.app/Contents/MacOS/' | realpath }}"

    - name: Install from installer.app
      command: "/Volumes/Endpoint\\ for\\ MAC/SetupDownloader.app/Contents/MacOS/SetupDownloader"
      become: yes

    - name: Debug file existence
      debug:
        msg: "File exists: {{ '/Volumes/Endpoint for MAC/SetupDownloader.app/Contents/MacOS/SetupDownloader' | realpath }}"

    - name: Unmount DMG
      command: hdiutil detach "/Volumes/Endpoint for MAC"

    - name: Pause to allow installation to complete
      pause:
        seconds: 10

    - name: Delete .dmg specified
      file:
        path: "/tmp/bit_defender.dmg"
        state: absent
