---
- name: Check .dmg installer checksum and scan for virus
  hosts: localhost  # Run tasks on the Ansible control node
  gather_facts: false
  vars:
    check_file: "/tmp/blink_central.scpt"
  
  tasks:
    - name: Install ClamAV
      become: yes
      package:
        name: clamav
        state: present

    - name: Scan .scpt file with ClamAV
      command: clamscan --stdout "{{ check_file }}"
      register: clamav_result
      changed_when: false

    - name: Fail if virus found
      fail:
        msg: "Virus detected in the downloaded file!"
      when: "'FOUND' in clamav_result.stdout"

- hosts: "{{ target }}"
  gather_facts: false
  tasks:
  - name: create shortcut
    copy:
      dest: "/tmp/blink_central.scpt"
      content: |
        tell application "Finder" to open location "smb://blink_central"

  - name: turn .scpt to app
    command: osacompile -o /Applications/blink_central.app /tmp/blink_central.scpt

  - name: Delete .scpt specified
    file:
      path: /tmp/blink_central.scpt
      state: absent