---
- name: Check .dmg installer checksum and scan for virus
  hosts: localhost  # Run tasks on the Ansible control node
  gather_facts: false
  vars:
    file_contents: "{{ lookup('file', '/home/eng/border_control/discord_check.txt') }}"
    download_url: "https://discord.com/api/download?platform=osx"
    download_path: "/home/eng/apps/macOS/.tempDir/Discord.dmg"

  
  tasks:
    - name: Download the .dmg file
      get_url:
        url: "{{ download_url }}"
        dest: "{{ download_path }}"

    - name: Calculate the checksum of the downloaded file
      command: "shasum -a 256 '{{ download_path }}'"
      register: calculated_checksum
        
    - name: Compare checksum values
      assert:
        that: "{{ calculated_checksum.stdout.split()[0] == file_contents }}"
        msg: "Checksums do not match. File may be corrupted."

    - name: Install ClamAV
      become: yes
      package:
        name: clamav
        state: present

    - name: Scan .zip file with ClamAV
      command: clamscan --stdout "{{ download_path }}"
      register: clamav_result
      changed_when: false

    - name: Fail if virus found
      fail:
        msg: "Virus detected in the downloaded file!"
      when: "'FOUND' in clamav_result.stdout"

- name: Install Discord
  hosts: "{{ target }}"
  gather_facts: false
  tasks:
    - name: Check if .app exists
      stat:
        path: "/Applications/Discord.app"
      register: file_data

    - name: Change to .app.old if exists
      command: "mv /Applications/Discord.app /Applications/Discord.old"
      when: file_data.stat.exists

    - name: Download the .dmg file
      copy:
        src: /home/eng/apps/macOS/.tempDir/Discord.dmg
        dest: "/tmp/Discord.dmg"

    - name: Mount DMG
      command: hdiutil attach -nobrowse -mountpoint "/Volumes/Discord" "/tmp/Discord.dmg"
      register: mounted_volume

    - name: Copy App to Applications
      command: cp -R "/Volumes/Discord/Discord.app" /Applications/

    - name: Delete .old
      file:
        path: "/Applications/Discord.old"
        state: absent

    - name: Pause to allow installation to complete
      pause:
        seconds: 10

    - name: Unmount DMG
      command: hdiutil detach "/Volumes/Discord"

    - name: Delete .dmg specified
      file:
        path: "/tmp/Discord.dmg"
        state: absent
