---
- name: ClamAV
  hosts: localhost  # Run tasks on the Ansible control node
  gather_facts: false
  vars:
    check_file: "/home/eng/apps/googlechrome.dmg"
  
  tasks:
    - name: Install ClamAV
      become: yes
      package:
        name: clamav
        state: present

    - name: Scan .dmg file with ClamAV
      command: clamscan --stdout "{{ check_file }}"
      register: clamav_result
      changed_when: false

    - name: Fail if virus found
      fail:
        msg: "Virus detected in the downloaded file!"
      when: "'FOUND' in clamav_result.stdout"

- name: Install Google Drive
  hosts: "{{ target }}"
  gather_facts: false
  tasks:
    - name: Download the .dmg file
      copy:
        src: /home/eng/apps/googlechrome.dmg
        dest: "/tmp/googlechrome.dmg"

    - name: Mount DMG
      command: hdiutil attach -nobrowse -mountpoint "/Volumes/Google Chrome" "/tmp/googlechrome.dmg"
      register: mounted_volume

    - name: Copy App to Applications
      command: cp -R "/Volumes/Google Chrome/Google Chrome.app" /Applications/

    - name: Unmount DMG
      command: hdiutil detach "/Volumes/Google Chrome"

    - name: Pause to allow installation to complete
      pause:
        seconds: 10

    - name: Delete .dmg specified
      file:
        path: "/tmp/googlechrome.dmg"
        state: absent