---
- name: Check .dmg installer checksum
  hosts: "{{ target }}"
  gather_facts: false
  vars:
        file_contents: "{{ lookup('file', '/home/eng/border_control/gdrive_check.txt') }}"
  tasks:
    - name: Download the .dmg file
      get_url:
        url: "https://dl.google.com/drive-file-stream/GoogleDrive.dmg"
        dest: "/tmp/GoogleDrive.dmg"

    - name: Calculate the checksum of the downloaded file
      command: "shasum -a 256 '/tmp/GoogleDrive.dmg'"
      register: calculated_checksum
        
    - name: Compare checksum values
      assert:
        that: "{{ calculated_checksum.stdout.split()[0] == file_contents }}"
        msg: "Checksums do not match. File may be corrupted."
  
    - name: Mount DMG
      #command: hdiutil attach ./Downloads/tmp/slack.dmg -nobrowse
      command: hdiutil attach -nobrowse -mountpoint "/Volumes/GoogleDrive" "/tmp/GoogleDrive.dmg"
      register: mounted_volume

    - name: Install App
      command: sudo installer -pkg /Volumes/GoogleDrive/GoogleDrive.pkg -target /
      become: yes

    - name: Unmount DMG
      command: hdiutil detach "/Volumes/GoogleDrive"

    - name: Pause to allow installation to complete
      pause:
        seconds: 10

    - name: Delete .dmg specified
      file:
        path: "/tmp/GoogleDrive.dmg"
        state: absent