---
- name: Master Playbook Installer
  hosts: "{{ target }}"
  gather_facts: false
- import_playbook: tmp_dir.yaml
- import_playbook: blink_central_scpt_playbook.yaml
- import_playbook: teamviewer_host_install_playbook.yaml
- import_playbook: zoom_install_playbook.yaml
- import_playbook: slack_install_playbook.yaml
# - import_playbook: discord_install_playbook.yaml
- import_playbook: dropbox_install_playbook.yaml
- import_playbook: bitdefender_install_playbook.yaml
- import_playbook: forticlient_VPN_install_playbook.yaml
- import_playbook: google_chrome_install_playbook.yaml
- import_playbook: google_drive_install_playbook.yaml
- import_playbook: ibm_aspera_connect_install_playbook.yaml
- import_playbook: vlc_install_playbook.yaml
- import_playbook: sonos_install_playbook.yaml
- import_playbook: rv_player_install_playbooks.yaml
# - import_playbook: spotify_install_playbook.yaml
- import_playbook: whatsapp_install_playbook.yaml
- import_playbook: adobe_cc_install_playbook.yaml
- import_playbook: 365_office_install_playbook.yaml