---
- name: Check .dmg installer checksum
  hosts: "{{ target }}"
  gather_facts: false
  vars:
        file_contents: "{{ lookup('file', '/home/eng/border_control/rv_check.txt') }}"
  tasks:
    - name: Download the .dmg file
      get_url:
        url: "https://sg-software.ems.autodesk.com/deploy/rv/Current_Release/MacOS-release.dmg"
        dest: "/tmp/RV.dmg"

    - name: Calculate the checksum of the downloaded file
      command: "shasum -a 256 '/tmp/RV.dmg'"
      register: calculated_checksum
        
    - name: Compare checksum values
      assert:
        that: "{{ calculated_checksum.stdout.split()[0] == file_contents }}"
        msg: "Checksums do not match. File may be corrupted."
  
    - name: Mount DMG
      command: hdiutil attach -nobrowse -mountpoint "/Volumes/RV" "/tmp/RV.dmg"
      register: mounted_volume

    - name: Copy App to Applications
      command: cp -R "/Volumes/RV/RV.app" /Applications/

    - name: Unmount DMG
      command: hdiutil detach "/Volumes/RV"

    - name: Pause to allow installation to complete
      pause:
        seconds: 10

    - name: Delete .dmg specified
      file:
        path: "/tmp/RV.dmg"
        state: absent