---
- name: ClamAV
  hosts: localhost  # Run tasks on the Ansible control node
  gather_facts: false
  vars:
    file_contents: "{{ lookup('file', '/home/eng/border_control/slack_check.txt') }}"
    download_url: "https://slack.com/ssb/download-osx-universal"
    download_path: "/home/eng/apps/Slack.dmg"
  
  tasks:
    - name: Download the .dmg file
      get_url:
        url: "{{ download_url }}"
        dest: "{{ download_path }}"

    - name: Calculate the checksum of the downloaded file
      command: "shasum -a 256 '{{ download_path }}'"
      register: calculated_checksum
        
    - name: Compare checksum values
      assert:
        that: "{{ calculated_checksum.stdout.split()[0] == file_contents }}"
        msg: "Checksums do not match. File may be corrupted."

    - name: Install ClamAV
      become: yes
      package:
        name: clamav
        state: present

    - name: Scan .zip file with ClamAV
      command: clamscan --stdout "{{ download_path }}"
      register: clamav_result
      changed_when: false

    - name: Fail if virus found
      fail:
        msg: "Virus detected in the downloaded file!"
      when: "'FOUND' in clamav_result.stdout"

- name: Install Slack
  hosts: "{{ target }}"
  tasks:
    - name: Check if .app exists
      stat:
        path: "/Applications/Slack.app"
      register: file_data

    - name: Change to .app.old if exists
      command: "mv /Applications/Slack.app /Applications/Slack.old"
      when: file_data.stat.exists

    - name: Transfer the .dmg file to target hosts
      ansible.builtin.copy:
        src: "/home/eng/apps/Slack.dmg"
        dest: "/tmp/Slack.dmg"
  
    - name: Mount DMG
      command: hdiutil attach -nobrowse -mountpoint "/Volumes/Slack" "/tmp/Slack.dmg"
      register: mounted_volume

    - name: Copy App to Applications
      command: cp -R "/Volumes/Slack/Slack.app" /Applications/

    - name: Delete .old
      file:
        path: "/Applications/Slack.old"
        state: absent

    - name: Pause to allow installation to complete
      pause:
        seconds: 10
        
    - name: Unmount DMG
      command: hdiutil detach "/Volumes/Slack"

    - name: Delete .dmg specified
      file:
        path: "/tmp/Slack.dmg"
        state: absent