---
- name: Check .dmg installer checksum
  hosts: "{{ target }}"
  gather_facts: false
  vars:
        file_contents: "{{ lookup('file', '/home/eng/border_control/slack_check.txt') }}"
  tasks:
    - name: Check if .app exists
      stat:
        path: "/Applications/Slack.app"
      register: file_data

    - name: Change to .app.old if exists
      command: "mv /Applications/Slack.app /Applications/Slack.old"
      when: file_data.stat.exists

    - name: Download the .dmg file
      get_url:
        url: "https://slack.com/ssb/download-osx-universal"
        dest: "/tmp/Slack.dmg"

    - name: Calculate the checksum of the downloaded file
      command: "shasum -a 256 '/tmp/Slack.dmg'"
      register: calculated_checksum
        
    - name: Compare checksum values
      assert:
        that: "{{ calculated_checksum.stdout.split()[0] == file_contents }}"
        msg: "Checksums do not match. File may be corrupted."
  
    - name: Mount DMG
      command: hdiutil attach -nobrowse -mountpoint "/Volumes/Slack" "/tmp/Slack.dmg"
      register: mounted_volume

    - name: Copy App to Applications
      command: cp -R "/Volumes/Slack/Slack.app" /Applications/

    - name: Delete .old
      file:
        path: "/Applications/Slack.old"
        state: absent

    - name: Pause to allow installation to complete
      pause:
        seconds: 10
        
    - name: Unmount DMG
      command: hdiutil detach "/Volumes/Slack"

    - name: Delete .dmg specified
      file:
        path: "/tmp/Slack.dmg"
        state: absent