---
- name: Check .dmg installer checksum
  hosts: "{{ target }}"
  gather_facts: false
  vars:
        file_contents: "{{ lookup('file', '/home/eng/border_control/sonos_check.txt') }}"
  tasks:
    - name: Download the .dmg file
      get_url:
        url: "https://www.sonos.com/redir/controller_software_mac2"
        dest: "/tmp/Sonos.dmg"

    - name: Calculate the checksum of the downloaded file
      command: "shasum -a 256 '/tmp/Sonos.dmg'"
      register: calculated_checksum
        
    - name: Compare checksum values
      assert:
        that: "{{ calculated_checksum.stdout.split()[0] == file_contents }}"
        msg: "Checksums do not match. File may be corrupted."
  
    - name: Mount DMG
      command: hdiutil attach -nobrowse -mountpoint "/Volumes/Sonos" "/tmp/Sonos.dmg"
      register: mounted_volume

    - name: Copy App to Applications
      command: cp -R "/Volumes/Sonos/Sonos.app" /Applications/

    - name: Unmount DMG
      command: hdiutil detach "/Volumes/Sonos"

    - name: Pause to allow installation to complete
      pause:
        seconds: 10

    - name: Delete .dmg specified
      file:
        path: "/tmp/Sonos.dmg"
        state: absent