---
- name: Check .dmg installer checksum and scan for virus
  hosts: localhost  # Run tasks on the Ansible control node
  gather_facts: false
  vars:
    file_contents: "{{ lookup('file', '/home/eng/border_control/wacom_check.txt') }}"
    download_url: "https://cdn.wacom.com/u/productsupport/drivers/mac/professional/WacomTablet_6.4.5-3.dmg"
    download_path: "/home/eng/apps/wacom.dmg"

  tasks:
    - name: Download the .zip file
      get_url:
        url: "{{ download_url }}"
        dest: "{{ download_path }}"

    - name: Calculate the checksum of the downloaded file
      command: "shasum -a 256 '{{ download_path }}'"
      register: calculated_checksum
        
    - name: Compare checksum values
      assert:
        that: "{{ calculated_checksum.stdout.split()[0] == file_contents }}"
        msg: "Checksums do not match. File may be corrupted."

    - name: Install ClamAV
      become: yes
      package:
        name: clamav
        state: present

    - name: Scan downloaded file with ClamAV
      command: clamscan --stdout "{{ download_path }}"
      register: clamav_result
      changed_when: false

    - name: Fail if virus found
      fail:
        msg: "Virus detected in the downloaded file!"
      when: "'FOUND' in clamav_result.stdout"

- name: Install Wacom
  hosts: "{{ target }}"
  gather_facts: false
  tasks:
    - name: Transfer the .dmg file to target hosts
      ansible.builtin.copy:
        src: "/home/eng/apps/wacom.dmg"
        dest: "/tmp/wacom.dmg"
  
    - name: Mount DMG
      command: hdiutil attach -nobrowse -mountpoint "/Volumes/WacomTablet" "/tmp/wacom.dmg"
      register: mounted_volume

    - name: Install from installer.pkg
      command: "sudo installer -pkg /Volumes/WacomTablet/Install\\ Wacom\\ Tablet.pkg -target /"
      become: yes

    - name: Pause to allow installation to complete
      pause:
        seconds: 15
    
    - name: Unmount DMG
      command: hdiutil detach "/Volumes/WacomTablet"

    - name: Delete .dmg specified
      file:
        path: "/tmp/wacom.dmg"
        state: absent