---
- name: Install zoom.us 
  hosts: " {{ target }} "
  gather_facts: false
  vars:
        file_contents: "{{ lookup('file', '/home/eng/border_control/zoom_check.txt') }}"
  tasks:
    - name: Download the .pkg file
      get_url:
        url: "https://zoom.us/client/5.17.5.29101/zoomusInstallerFull.pkg"
        dest: "/tmp/zoom.pkg"

    - name: Calculate the checksum of the downloaded file
      command: "shasum -a 256 '/tmp/zoom.pkg'"
      register: calculated_checksum
        
    - name: Compare checksum values
      assert:
        that: "{{ calculated_checksum.stdout.split()[0] == file_contents }}"
        msg: "Checksums do not match. File may be corrupted."

    - name: Install App
      command: sudo installer -store -pkg /tmp/zoom.pkg -target /
      become: yes

    - name: Delete .dmg specified
      file:
        path: "/tmp/zoom.pkg"
        state: absent

