---
- name: Check .dmg installer checksum and scan for virus
  hosts: localhost  # Run tasks on the Ansible control node
  gather_facts: false
  vars:
    file_contents: "{{ lookup('file', '/home/eng/border_control/zoom_check.txt') }}"
    download_url: "https://zoom.us/client/6.0.2.33403/zoomusInstallerFull.pkg?archType=arm64"
    download_path: "/home/eng/apps/zoom.pkg"

  tasks:
    - name: Download the .dmg file
      get_url:
        url: "{{ download_url }}"
        dest: "{{ download_path }}"

    - name: Calculate the checksum of the downloaded file
      command: "shasum -a 256 '{{ download_path }}'"
      register: calculated_checksum
        
    - name: Compare checksum values
      assert:
        that: "{{ calculated_checksum.stdout.split()[0] == file_contents }}"
        msg: "Checksums do not match. File may be corrupted."

    - name: Install ClamAV
      become: yes
      package:
        name: clamav
        state: present

    - name: Scan downloaded file with ClamAV
      command: clamscan --stdout "{{ download_path }}"
      register: clamav_result
      changed_when: false

    - name: Fail if virus found
      fail:
        msg: "Virus detected in the downloaded file!"
      when: "'FOUND' in clamav_result.stdout"

- name: Install zoom.us 
  hosts: " {{ target }} "
  gather_facts: false
  tasks:
    - name: Transfer the .pkg file to target hosts
      ansible.builtin.copy:
        src: "/home/eng/apps/zoom.pkg"
        dest: "/tmp/zoom.pkg"

    - name: Install App
      command: sudo installer -store -pkg /tmp/zoom.pkg -target /
      become: yes

    - name: Delete .dmg specified
      file:
        path: "/tmp/zoom.pkg"
        state: absent

