---
- name: Check .dmg installer checksum
  hosts: "{{ target }}"
  gather_facts: false
  vars:
        file_contents: "{{ lookup('file', '/home/eng/border_control/djv_check.txt') }}"
  tasks:
    - name: Download the .dmg file
      copy:
        src: /home/eng/ansible/ansible-playbook/apps/DJV-1.3.0-Darwin.dmg
        dest: "/tmp/DJV.dmg"

    # - name: Calculate the checksum of the downloaded file
    #   command: "shasum -a 256 '/tmp/DJV.dmg'"
    #   register: calculated_checksum
        
    # - name: Compare checksum values
    #   assert:
    #     that: "{{ calculated_checksum.stdout.split()[0] == file_contents }}"
    #     msg: "Checksums do not match. File may be corrupted."

    - name: Debug path existence
      debug:
        msg: "Path exists: {{ '/Volumes/DJV-1.3.0-Darwin' | realpath }}"

  
    - name: Mount DMG
      ansible.builtin.expect:
        command: hdiutil attach -nobrowse -mountpoint "/Volumes/DJV-1.3.0-Darwin" "/tmp/DJV.dmg"
        responses:
          "Agree": "\n"
          "Copyright (c) 2004-2019 Darby Johnston": "\n"  # Respond to the copyright notice
          "Redistribution and use in source and binary forms": "\n"  # Respond to the terms and conditions
      become: yes

    - name: Install from installer.app
      command: "/Volumes/DJV-1.3.0-Darwin/DJV/Contents/MacOS/DJV"
      become: yes
    
    - name: Unmount DMG
      command: hdiutil detach "/Volumes/DJV-1.3.0-Darwin"

    - name: Pause to allow installation to complete
      pause:
        seconds: 10

    - name: Delete .dmg specified
      file:
        path: "/tmp/DJV.dmg"
        state: absent